services:
  analysis-pipeline:
    build:
      context: ./analysis-pipeline
      dockerfile: dockerfile
    ports:
      - "8000:8000"

  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      PIPELINE_URL: "http://analysis-pipeline:8000"
    depends_on:
      - analysis-pipeline
