# The different containers that will be running
services:
  review-pipeline:
    build:
      context: ./review-pipeline
      dockerfile: dockerfile
  analysis-pipeline:
    build:
      context: ./analysis-pipeline
      dockerfile: dockerfile
    secrets:
      - EDGAR_IDENTITY
  orchestrator:
    # Docker build
    build:
      context: ./orchestrator
      dockerfile: dockerfile
    # port exposure
    ports:
      - "8080:8080"
    # Server talks to analysis-pipeline through the internal docker network
    environment:
      PIPELINE_URL: "http://analysis-pipeline:8000"
    # This container cannot run without analysis pipeline
    depends_on:
      - analysis-pipeline
      - review-pipeline

# Define relevant secrets needed
secrets:
  EDGAR_IDENTITY:
    file: ./secrets/EDGAR_IDENTITY.txt
