# docker-compose.prod.yml — run this one on EC2
services:
  analysis-pipeline:
    image: 857360184083.dkr.ecr.us-east-2.amazonaws.com/snowball/analysis-pipeline:2469046
    restart: unless-stopped
    secrets:
      - EDGAR_IDENTITY
    environment:
      - PYTHONUNBUFFERED=1

  orchestrator:
    image: 857360184083.dkr.ecr.us-east-2.amazonaws.com/snowball/orchestrator:e1ff471
    ports:
      - "8080:8080"
    environment:
      PIPELINE_URL: "http://analysis-pipeline:8000"
    depends_on:
      - analysis-pipeline
    restart: unless-stopped

secrets:
  EDGAR_IDENTITY:
    file: ./secrets/EDGAR_IDENTITY.txt