apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis-pipeline
  template:
    metadata:
      labels:
        app: analysis-pipeline
    spec:
      serviceAccountName: analysis-pipeline
      containers:
        - name: analysis-pipeline
          image: 857360184083.dkr.ecr.us-east-2.amazonaws.com/snowball/analysis-pipeline:358f6a7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: AWS_DEFAULT_REGION
              value: us-east-2