# Use Python
FROM python:3.12-slim
# Directory in the actuall VM
WORKDIR /app
# Copy requirements first so that they are cached, and only re-pipinstall on new runs
COPY requirements.txt .
# Pip install
RUN pip install -r requirements.txt

# Copy the application source
COPY . .

# Remove trailing \r that is corrupting for windows --> linux
RUN sed -i 's/\r$//' /app/entrypoint.sh

# Make file runable
RUN chmod +x /app/entrypoint.sh

# Entrypoint now runs the script first (sets up secret env var, then execs CMD)
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "app:create_app()"]

# The port its being exposed on, documentation really
EXPOSE 8000